apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipesite
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recipesite-labels
  template:
    metadata:
      labels:
        app: recipesite-labels
    spec:
      containers:
      - name: recipesite-container
        image: skannte/recipesite-image:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: BillingServicePath
          value: /usr/data
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: recipesite-volume
          mountPath: /usr/data
      volumes:
      - name: recipesite-volume
        persistentVolumeClaim:
          claimName: sqlite-pvc

